root = "."

[build]
  bin = "./tmp/api/main"
  cmd = "make build"
  exclude_dir = ["assets", "tmp", "vendor", "logs", "goose"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "html"]
  delay = 1000
  log = "build-errors.log"
  stop_on_error = true

[misc]
  clean_on_exit = true