services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"

  # for more services

volumes:
  db_data:
  app_data: