services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      context: .
      target: ${APP_ENV}
    volumes:
      - ${TRACK_DIR:-app_data}:/app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env

  # for more services

volumes:
  db_data:
  app_data: